/**
 * era-data.js
 * 元号データ定義ファイル
 *
 * 各元号は以下の構造を持つ:
 *   name      - 元号名
 *   startYear - 開始西暦年
 *   endYear   - 終了西暦年（次の元号の開始年と同じ。現行元号は null）
 *   startMonth - 改元月（将来拡張用、現在は null）
 *   startDay   - 改元日（将来拡張用、現在は null）
 *
 * 注意: endYear は「その元号が使われた最後の年」であり、
 *       次の元号の startYear と重複する場合がある（年の途中で改元されるため）。
 *       元号が存在しなかった無元号期（例：654〜686年）は、配列に定義しないことで
 *       自動的に「元号なし（西暦のみ）」として正しく判定されます。
 */

const ERA_DATA = [
  // --- 飛鳥・奈良時代 ---
  { name: "大化", startYear: 645, endYear: 650, startMonth: null, startDay: null },
  { name: "白雉", startYear: 650, endYear: 654, startMonth: null, startDay: null },
  // 654〜686年は無元号期
  { name: "朱鳥", startYear: 686, endYear: 686, startMonth: null, startDay: null },
  // 686〜701年は無元号期
  { name: "大宝", startYear: 701, endYear: 704, startMonth: null, startDay: null },
  { name: "慶雲", startYear: 704, endYear: 708, startMonth: null, startDay: null },
  { name: "和銅", startYear: 708, endYear: 715, startMonth: null, startDay: null },
  { name: "霊亀", startYear: 715, endYear: 717, startMonth: null, startDay: null },
  { name: "養老", startYear: 717, endYear: 724, startMonth: null, startDay: null },
  { name: "神亀", startYear: 724, endYear: 729, startMonth: null, startDay: null },
  { name: "天平", startYear: 729, endYear: 749, startMonth: null, startDay: null },
  { name: "天平感宝", startYear: 749, endYear: 749, startMonth: null, startDay: null },
  { name: "天平勝宝", startYear: 749, endYear: 757, startMonth: null, startDay: null },
  { name: "天平宝字", startYear: 757, endYear: 765, startMonth: null, startDay: null },
  { name: "天平神護", startYear: 765, endYear: 767, startMonth: null, startDay: null },
  { name: "神護景雲", startYear: 767, endYear: 770, startMonth: null, startDay: null },
  { name: "宝亀", startYear: 770, endYear: 781, startMonth: null, startDay: null },
  { name: "天応", startYear: 781, endYear: 782, startMonth: null, startDay: null },
  { name: "延暦", startYear: 782, endYear: 806, startMonth: null, startDay: null },

  // --- 平安時代 ---
  { name: "大同", startYear: 806, endYear: 810, startMonth: null, startDay: null },
  { name: "弘仁", startYear: 810, endYear: 824, startMonth: null, startDay: null },
  { name: "天長", startYear: 824, endYear: 834, startMonth: null, startDay: null },
  { name: "承和", startYear: 834, endYear: 848, startMonth: null, startDay: null },
  { name: "嘉祥", startYear: 848, endYear: 851, startMonth: null, startDay: null },
  { name: "仁寿", startYear: 851, endYear: 854, startMonth: null, startDay: null },
  { name: "斉衡", startYear: 854, endYear: 857, startMonth: null, startDay: null },
  { name: "天安", startYear: 857, endYear: 859, startMonth: null, startDay: null },
  { name: "貞観", startYear: 859, endYear: 877, startMonth: null, startDay: null },
  { name: "元慶", startYear: 877, endYear: 885, startMonth: null, startDay: null },
  { name: "仁和", startYear: 885, endYear: 889, startMonth: null, startDay: null },
  { name: "寛平", startYear: 889, endYear: 898, startMonth: null, startDay: null },
  { name: "昌泰", startYear: 898, endYear: 901, startMonth: null, startDay: null },
  { name: "延喜", startYear: 901, endYear: 923, startMonth: null, startDay: null },
  { name: "延長", startYear: 923, endYear: 931, startMonth: null, startDay: null },
  { name: "承平", startYear: 931, endYear: 938, startMonth: null, startDay: null },
  { name: "天慶", startYear: 938, endYear: 947, startMonth: null, startDay: null },
  { name: "天暦", startYear: 947, endYear: 957, startMonth: null, startDay: null },
  { name: "天徳", startYear: 957, endYear: 961, startMonth: null, startDay: null },
  { name: "応和", startYear: 961, endYear: 964, startMonth: null, startDay: null },
  { name: "康保", startYear: 964, endYear: 968, startMonth: null, startDay: null },
  { name: "安和", startYear: 968, endYear: 970, startMonth: null, startDay: null },
  { name: "天禄", startYear: 970, endYear: 973, startMonth: null, startDay: null },
  { name: "天延", startYear: 973, endYear: 976, startMonth: null, startDay: null },
  { name: "貞元", startYear: 976, endYear: 978, startMonth: null, startDay: null },
  { name: "天元", startYear: 978, endYear: 983, startMonth: null, startDay: null },
  { name: "永観", startYear: 983, endYear: 985, startMonth: null, startDay: null },
  { name: "寛和", startYear: 985, endYear: 987, startMonth: null, startDay: null },
  { name: "永延", startYear: 987, endYear: 989, startMonth: null, startDay: null },
  { name: "永祚", startYear: 989, endYear: 990, startMonth: null, startDay: null },
  { name: "正暦", startYear: 990, endYear: 995, startMonth: null, startDay: null },
  { name: "長徳", startYear: 995, endYear: 999, startMonth: null, startDay: null },
  { name: "長保", startYear: 999, endYear: 1004, startMonth: null, startDay: null },
  { name: "寛弘", startYear: 1004, endYear: 1012, startMonth: null, startDay: null },
  { name: "長和", startYear: 1012, endYear: 1017, startMonth: null, startDay: null },
  { name: "寛仁", startYear: 1017, endYear: 1021, startMonth: null, startDay: null },
  { name: "治安", startYear: 1021, endYear: 1024, startMonth: null, startDay: null },
  { name: "万寿", startYear: 1024, endYear: 1028, startMonth: null, startDay: null },
  { name: "長元", startYear: 1028, endYear: 1037, startMonth: null, startDay: null },
  { name: "長暦", startYear: 1037, endYear: 1040, startMonth: null, startDay: null },
  { name: "長久", startYear: 1040, endYear: 1044, startMonth: null, startDay: null },
  { name: "寛徳", startYear: 1044, endYear: 1046, startMonth: null, startDay: null },
  { name: "永承", startYear: 1046, endYear: 1053, startMonth: null, startDay: null },
  { name: "天喜", startYear: 1053, endYear: 1058, startMonth: null, startDay: null },
  { name: "康平", startYear: 1058, endYear: 1065, startMonth: null, startDay: null },
  { name: "治暦", startYear: 1065, endYear: 1069, startMonth: null, startDay: null },
  { name: "延久", startYear: 1069, endYear: 1074, startMonth: null, startDay: null },
  { name: "承保", startYear: 1074, endYear: 1077, startMonth: null, startDay: null },
  { name: "承暦", startYear: 1077, endYear: 1081, startMonth: null, startDay: null },
  { name: "永保", startYear: 1081, endYear: 1084, startMonth: null, startDay: null },
  { name: "応徳", startYear: 1084, endYear: 1087, startMonth: null, startDay: null },
  { name: "寛治", startYear: 1087, endYear: 1094, startMonth: null, startDay: null },
  { name: "嘉保", startYear: 1094, endYear: 1096, startMonth: null, startDay: null },
  { name: "永長", startYear: 1096, endYear: 1097, startMonth: null, startDay: null },
  { name: "承徳", startYear: 1097, endYear: 1099, startMonth: null, startDay: null },
  { name: "康和", startYear: 1099, endYear: 1104, startMonth: null, startDay: null },
  { name: "長治", startYear: 1104, endYear: 1106, startMonth: null, startDay: null },
  { name: "嘉承", startYear: 1106, endYear: 1108, startMonth: null, startDay: null },
  { name: "天仁", startYear: 1108, endYear: 1110, startMonth: null, startDay: null },
  { name: "天永", startYear: 1110, endYear: 1113, startMonth: null, startDay: null },
  { name: "永久", startYear: 1113, endYear: 1118, startMonth: null, startDay: null },
  { name: "元永", startYear: 1118, endYear: 1120, startMonth: null, startDay: null },
  { name: "保安", startYear: 1120, endYear: 1124, startMonth: null, startDay: null },
  { name: "天治", startYear: 1124, endYear: 1126, startMonth: null, startDay: null },
  { name: "大治", startYear: 1126, endYear: 1131, startMonth: null, startDay: null },
  { name: "天承", startYear: 1131, endYear: 1132, startMonth: null, startDay: null },
  { name: "長承", startYear: 1132, endYear: 1135, startMonth: null, startDay: null },
  { name: "保延", startYear: 1135, endYear: 1141, startMonth: null, startDay: null },
  { name: "永治", startYear: 1141, endYear: 1142, startMonth: null, startDay: null },
  { name: "康治", startYear: 1142, endYear: 1144, startMonth: null, startDay: null },
  { name: "天養", startYear: 1144, endYear: 1145, startMonth: null, startDay: null },
  { name: "久安", startYear: 1145, endYear: 1151, startMonth: null, startDay: null },
  { name: "仁平", startYear: 1151, endYear: 1154, startMonth: null, startDay: null },
  { name: "久寿", startYear: 1154, endYear: 1156, startMonth: null, startDay: null },
  { name: "保元", startYear: 1156, endYear: 1159, startMonth: null, startDay: null },
  { name: "平治", startYear: 1159, endYear: 1160, startMonth: null, startDay: null },
  { name: "永暦", startYear: 1160, endYear: 1161, startMonth: null, startDay: null },
  { name: "応保", startYear: 1161, endYear: 1163, startMonth: null, startDay: null },
  { name: "長寛", startYear: 1163, endYear: 1165, startMonth: null, startDay: null },
  { name: "永万", startYear: 1165, endYear: 1166, startMonth: null, startDay: null },
  { name: "仁安", startYear: 1166, endYear: 1169, startMonth: null, startDay: null },
  { name: "嘉応", startYear: 1169, endYear: 1171, startMonth: null, startDay: null },
  { name: "承安", startYear: 1171, endYear: 1175, startMonth: null, startDay: null },
  { name: "安元", startYear: 1175, endYear: 1177, startMonth: null, startDay: null },
  { name: "治承", startYear: 1177, endYear: 1181, startMonth: null, startDay: null },
  { name: "養和", startYear: 1181, endYear: 1182, startMonth: null, startDay: null },
  { name: "寿永", startYear: 1182, endYear: 1184, startMonth: null, startDay: null },
  { name: "元暦", startYear: 1184, endYear: 1185, startMonth: null, startDay: null },
  { name: "文治", startYear: 1185, endYear: 1190, startMonth: null, startDay: null },
  { name: "建久", startYear: 1190, endYear: 1199, startMonth: null, startDay: null },

  // --- 鎌倉時代 ---
  { name: "正治", startYear: 1199, endYear: 1201, startMonth: null, startDay: null },
  { name: "建仁", startYear: 1201, endYear: 1204, startMonth: null, startDay: null },
  { name: "元久", startYear: 1204, endYear: 1206, startMonth: null, startDay: null },
  { name: "建永", startYear: 1206, endYear: 1207, startMonth: null, startDay: null },
  { name: "承元", startYear: 1207, endYear: 1211, startMonth: null, startDay: null },
  { name: "建暦", startYear: 1211, endYear: 1213, startMonth: null, startDay: null },
  { name: "建保", startYear: 1213, endYear: 1219, startMonth: null, startDay: null },
  { name: "承久", startYear: 1219, endYear: 1222, startMonth: null, startDay: null },
  { name: "貞応", startYear: 1222, endYear: 1224, startMonth: null, startDay: null },
  { name: "元仁", startYear: 1224, endYear: 1225, startMonth: null, startDay: null },
  { name: "嘉禄", startYear: 1225, endYear: 1227, startMonth: null, startDay: null },
  { name: "安貞", startYear: 1227, endYear: 1229, startMonth: null, startDay: null },
  { name: "寛喜", startYear: 1229, endYear: 1232, startMonth: null, startDay: null },
  { name: "貞永", startYear: 1232, endYear: 1233, startMonth: null, startDay: null },
  { name: "天福", startYear: 1233, endYear: 1234, startMonth: null, startDay: null },
  { name: "文暦", startYear: 1234, endYear: 1235, startMonth: null, startDay: null },
  { name: "嘉禎", startYear: 1235, endYear: 1238, startMonth: null, startDay: null },
  { name: "暦仁", startYear: 1238, endYear: 1239, startMonth: null, startDay: null },
  { name: "延応", startYear: 1239, endYear: 1240, startMonth: null, startDay: null },
  { name: "仁治", startYear: 1240, endYear: 1243, startMonth: null, startDay: null },
  { name: "寛元", startYear: 1243, endYear: 1247, startMonth: null, startDay: null },
  { name: "宝治", startYear: 1247, endYear: 1249, startMonth: null, startDay: null },
  { name: "建長", startYear: 1249, endYear: 1256, startMonth: null, startDay: null },
  { name: "康元", startYear: 1256, endYear: 1257, startMonth: null, startDay: null },
  { name: "正嘉", startYear: 1257, endYear: 1259, startMonth: null, startDay: null },
  { name: "正元", startYear: 1259, endYear: 1260, startMonth: null, startDay: null },
  { name: "文応", startYear: 1260, endYear: 1261, startMonth: null, startDay: null },
  { name: "弘長", startYear: 1261, endYear: 1264, startMonth: null, startDay: null },
  { name: "文永", startYear: 1264, endYear: 1275, startMonth: null, startDay: null },
  { name: "建治", startYear: 1275, endYear: 1278, startMonth: null, startDay: null },
  { name: "弘安", startYear: 1278, endYear: 1288, startMonth: null, startDay: null },
  { name: "正応", startYear: 1288, endYear: 1293, startMonth: null, startDay: null },
  { name: "永仁", startYear: 1293, endYear: 1299, startMonth: null, startDay: null },
  { name: "正安", startYear: 1299, endYear: 1302, startMonth: null, startDay: null },
  { name: "乾元", startYear: 1302, endYear: 1303, startMonth: null, startDay: null },
  { name: "嘉元", startYear: 1303, endYear: 1306, startMonth: null, startDay: null },
  { name: "徳治", startYear: 1306, endYear: 1308, startMonth: null, startDay: null },
  { name: "延慶", startYear: 1308, endYear: 1311, startMonth: null, startDay: null },
  { name: "応長", startYear: 1311, endYear: 1312, startMonth: null, startDay: null },
  { name: "正和", startYear: 1312, endYear: 1317, startMonth: null, startDay: null },
  { name: "文保", startYear: 1317, endYear: 1319, startMonth: null, startDay: null },
  { name: "元応", startYear: 1319, endYear: 1321, startMonth: null, startDay: null },
  { name: "元亨", startYear: 1321, endYear: 1324, startMonth: null, startDay: null },
  { name: "正中", startYear: 1324, endYear: 1326, startMonth: null, startDay: null },
  { name: "嘉暦", startYear: 1326, endYear: 1329, startMonth: null, startDay: null },
  { name: "元徳", startYear: 1329, endYear: 1332, startMonth: null, startDay: null },
  { name: "元弘", startYear: 1331, endYear: 1334, startMonth: null, startDay: null },

  // --- 南北朝・室町時代（京都宣明暦に合わせ北朝ベース） ---
  { name: "建武", startYear: 1334, endYear: 1338, startMonth: null, startDay: null },
  { name: "暦応", startYear: 1338, endYear: 1342, startMonth: null, startDay: null },
  { name: "康永", startYear: 1342, endYear: 1345, startMonth: null, startDay: null },
  { name: "貞和", startYear: 1345, endYear: 1350, startMonth: null, startDay: null },
  { name: "観応", startYear: 1350, endYear: 1352, startMonth: null, startDay: null },
  { name: "文和", startYear: 1352, endYear: 1356, startMonth: null, startDay: null },
  { name: "延文", startYear: 1356, endYear: 1361, startMonth: null, startDay: null },
  { name: "康安", startYear: 1361, endYear: 1362, startMonth: null, startDay: null },
  { name: "貞治", startYear: 1362, endYear: 1368, startMonth: null, startDay: null },
  { name: "応安", startYear: 1368, endYear: 1375, startMonth: null, startDay: null },
  { name: "永和", startYear: 1375, endYear: 1379, startMonth: null, startDay: null },
  { name: "康暦", startYear: 1379, endYear: 1381, startMonth: null, startDay: null },
  { name: "永徳", startYear: 1381, endYear: 1384, startMonth: null, startDay: null },
  { name: "至徳", startYear: 1384, endYear: 1387, startMonth: null, startDay: null },
  { name: "嘉慶", startYear: 1387, endYear: 1389, startMonth: null, startDay: null },
  { name: "康応", startYear: 1389, endYear: 1390, startMonth: null, startDay: null },
  { name: "明徳", startYear: 1390, endYear: 1394, startMonth: null, startDay: null },
  { name: "応永", startYear: 1394, endYear: 1428, startMonth: null, startDay: null },
  { name: "正長", startYear: 1428, endYear: 1429, startMonth: null, startDay: null },
  { name: "永享", startYear: 1429, endYear: 1441, startMonth: null, startDay: null },
  { name: "嘉吉", startYear: 1441, endYear: 1444, startMonth: null, startDay: null },
  { name: "文安", startYear: 1444, endYear: 1449, startMonth: null, startDay: null },
  { name: "宝徳", startYear: 1449, endYear: 1452, startMonth: null, startDay: null },
  { name: "享徳", startYear: 1452, endYear: 1455, startMonth: null, startDay: null },
  { name: "康正", startYear: 1455, endYear: 1457, startMonth: null, startDay: null },
  { name: "長禄", startYear: 1457, endYear: 1460, startMonth: null, startDay: null },
  { name: "寛正", startYear: 1460, endYear: 1466, startMonth: null, startDay: null },
  { name: "文正", startYear: 1466, endYear: 1467, startMonth: null, startDay: null },

  // --- 戦国〜江戸〜近代以降 ---
  { name: "応仁", startYear: 1467, endYear: 1469, startMonth: null, startDay: null },
  { name: "文明", startYear: 1469, endYear: 1487, startMonth: null, startDay: null },
  { name: "長享", startYear: 1487, endYear: 1489, startMonth: null, startDay: null },
  { name: "延徳", startYear: 1489, endYear: 1492, startMonth: null, startDay: null },
  { name: "明応", startYear: 1492, endYear: 1501, startMonth: null, startDay: null },
  { name: "文亀", startYear: 1501, endYear: 1504, startMonth: null, startDay: null },
  { name: "永正", startYear: 1504, endYear: 1521, startMonth: null, startDay: null },
  { name: "大永", startYear: 1521, endYear: 1528, startMonth: null, startDay: null },
  { name: "享禄", startYear: 1528, endYear: 1532, startMonth: null, startDay: null },
  { name: "天文", startYear: 1532, endYear: 1555, startMonth: null, startDay: null },
  { name: "弘治", startYear: 1555, endYear: 1558, startMonth: null, startDay: null },
  { name: "永禄", startYear: 1558, endYear: 1570, startMonth: null, startDay: null },
  { name: "元亀", startYear: 1570, endYear: 1573, startMonth: null, startDay: null },
  { name: "天正", startYear: 1573, endYear: 1592, startMonth: null, startDay: null },
  { name: "文禄", startYear: 1592, endYear: 1596, startMonth: null, startDay: null },
  { name: "慶長", startYear: 1596, endYear: 1615, startMonth: null, startDay: null },
  { name: "元和", startYear: 1615, endYear: 1624, startMonth: null, startDay: null },
  { name: "寛永", startYear: 1624, endYear: 1644, startMonth: null, startDay: null },
  { name: "正保", startYear: 1644, endYear: 1648, startMonth: null, startDay: null },
  { name: "慶安", startYear: 1648, endYear: 1652, startMonth: null, startDay: null },
  { name: "承応", startYear: 1652, endYear: 1655, startMonth: null, startDay: null },
  { name: "明暦", startYear: 1655, endYear: 1658, startMonth: null, startDay: null },
  { name: "万治", startYear: 1658, endYear: 1661, startMonth: null, startDay: null },
  { name: "寛文", startYear: 1661, endYear: 1673, startMonth: null, startDay: null },
  { name: "延宝", startYear: 1673, endYear: 1681, startMonth: null, startDay: null },
  { name: "天和", startYear: 1681, endYear: 1684, startMonth: null, startDay: null },
  { name: "貞享", startYear: 1684, endYear: 1688, startMonth: null, startDay: null },
  { name: "元禄", startYear: 1688, endYear: 1704, startMonth: null, startDay: null },
  { name: "宝永", startYear: 1704, endYear: 1711, startMonth: null, startDay: null },
  { name: "正徳", startYear: 1711, endYear: 1716, startMonth: null, startDay: null },
  { name: "享保", startYear: 1716, endYear: 1736, startMonth: null, startDay: null },
  { name: "元文", startYear: 1736, endYear: 1741, startMonth: null, startDay: null },
  { name: "寛保", startYear: 1741, endYear: 1744, startMonth: null, startDay: null },
  { name: "延享", startYear: 1744, endYear: 1748, startMonth: null, startDay: null },
  { name: "寛延", startYear: 1748, endYear: 1751, startMonth: null, startDay: null },
  { name: "宝暦", startYear: 1751, endYear: 1764, startMonth: null, startDay: null },
  { name: "明和", startYear: 1764, endYear: 1772, startMonth: null, startDay: null },
  { name: "安永", startYear: 1772, endYear: 1781, startMonth: null, startDay: null },
  { name: "天明", startYear: 1781, endYear: 1789, startMonth: null, startDay: null },
  { name: "寛政", startYear: 1789, endYear: 1801, startMonth: null, startDay: null },
  { name: "享和", startYear: 1801, endYear: 1804, startMonth: null, startDay: null },
  { name: "文化", startYear: 1804, endYear: 1818, startMonth: null, startDay: null },
  { name: "文政", startYear: 1818, endYear: 1830, startMonth: null, startDay: null },
  { name: "天保", startYear: 1830, endYear: 1844, startMonth: null, startDay: null },
  { name: "弘化", startYear: 1844, endYear: 1848, startMonth: null, startDay: null },
  { name: "嘉永", startYear: 1848, endYear: 1854, startMonth: null, startDay: null },
  { name: "安政", startYear: 1854, endYear: 1860, startMonth: null, startDay: null },
  { name: "万延", startYear: 1860, endYear: 1861, startMonth: null, startDay: null },
  { name: "文久", startYear: 1861, endYear: 1864, startMonth: null, startDay: null },
  { name: "元治", startYear: 1864, endYear: 1865, startMonth: null, startDay: null },
  { name: "慶応", startYear: 1865, endYear: 1868, startMonth: null, startDay: null },
  { name: "明治", startYear: 1868, endYear: 1912, startMonth: null, startDay: null },
  { name: "大正", startYear: 1912, endYear: 1926, startMonth: null, startDay: null },
  { name: "昭和", startYear: 1926, endYear: 1989, startMonth: null, startDay: null },
  { name: "平成", startYear: 1989, endYear: 2019, startMonth: null, startDay: null },
  { name: "令和", startYear: 2019, endYear: null, startMonth: null, startDay: null }
];
